modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_authors}"
displayTest = "IGNORE_ALL_VERSION"
description = '''为 FTB Quests 提供剪贴板图片粘贴、章节画布文字、任务实体模型显示和视频播放等编辑增强功能。'''

[[mixins]]
config = "${mod_id}.mixins.json"

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "required"
versionRange = "${neo_version_range}"
ordering = "NONE"
side = "CLIENT"

[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "CLIENT"

[[dependencies.${mod_id}]]
modId = "ftbquests"
type = "required"
versionRange = "[${ftb_quests_version},)"
ordering = "AFTER"
side = "CLIENT"
